const actions = {
	COMPARE: "COMPARE",
	MIGRATE_TO_SOURCE: "MIGRATE_TO_SOURCE",
	MIGRATE_TO_TARGET: "MIGRATE_TO_TARGET",
	SAVE: "SAVE",
	HELP: "HELP",
	GENERATE_CONFIG: "GENERATE_CONFIG",
};

module.exports = actions;
